### PR TITLE
Open and bounce webhook classes

### LINKED ISSUE #40: BounceMessage and OpenMessage objects
When receiving posts from Webhooks, you have a class for PostmarkInboundMessage that can be used in ASP.NET MVC Web Api. I wasn't able to find matching classes for Bounce and Open?

I found PostmarkOpen and PostmarkBounce which are close but are missing some properties:

Open webhook also returns:

            public DateTime ReceivedAt { get; set; }
            public string Tag { get; set; }
            public string Recipient { get; set; }

Bounce webhook also returns:

            public int TypeCode { get; set; }
            public string Name { get; set; }

If these classes don't exist, did you want me to PR the classes I made?

### PR DESCRIPTION
**Pull request by NeilBostrom**
This resolves #40 by adding two classes that can be used to deserialise the payload for open and bounce webhooks.

### CODE REVIEW

**Comment by atheken** [comment]
Hey @NeilBostrom Thanks for the PR! In looking at this, I wonder if we should put these classes under a new namespace: `Postmark.Webhooks`, and then name them with a common convention `<use case>Payload`

**Comment by NeilBostrom** [comment]
@atheken  I had similar thoughts but didn't want to rock the boat with the existing Inbound class. I do definitely think its worth moving them out to their own namespace and tweak the class names. I preferred Message suffix to Payload as it matches the ASP.NET Web API naming syntax. I'm easy on either though.

Is it worth me duplicating up the PostmarkInboundMessage class into the new Postmark.Webhooks namespace with the other new classes? Maybe mark the old one as deprecated?

Also, currently I'm inheriting PostmarkBounce and PostmarkOpen for all the properties of the webhook, will this ever differ between the APIs? Is it worth me duplicating the properties into the webhook classes and maintain them separately?

**Comment by atheken** [comment]
By all means, Rock it! :-D

The Message suffix makes sense, so let's go with that. 

You can certainly also subclass the base classes in `Postmark` from the new classes in `Postmark.Webhooks`, I'd prefer this over duplicating/deprecating/removing the existing classes. I don't know if the API will ever evolve to something where this doesn't make sense, but that is a simple refactoring to make a `Base` class with the shared properties if the day every comes.

**Comment by NeilBostrom** [comment]
@atheken Take a look and see what you think. I've moved the new classes into their own class files. 

I duplicated up PostmarkInboundMessage to be PostmarkInboundWebhookMessage in the Postmark.Webhooks namespace. Also added FromName which I spotted was missing from this class and is sent in the APIs.

**Pull request merged**
